"""
Medical AI Assistant API - Fixed Note Generation
"""

import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''

from fastapi import FastAPI, HTTPException, File, UploadFile, status, Depends, Response
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import requests
import logging
import base64
from typing import Optional, List
from PIL import Image
from io import BytesIO
from sqlalchemy import or_
from datetime import datetime
from fastapi import Query
import time

# AUTH IMPORTS
from auth import (
    get_current_user,
    UserOut,
    Token,
    UserCreate,
    register_user,
    get_db,
    OAuth2PasswordRequestForm,
    get_user_by_email,
    verify_password,
    create_access_token,
    Session,
    ConsultationHistory,
)

# TTS imports
try:
    from kokoro import KPipeline
    import numpy as np
    import soundfile as sf
    import io
    TTS_AVAILABLE = True
except ImportError as e:
    KPipeline = None
    TTS_AVAILABLE = False
    print(f"TTS not available: {e}")

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Medical AI Assistant API",
    description="API for medical documentation using medllama2 and qwen2.5vl:7b",
    version="1.0"
)

# Enable CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ollama configuration
OLLAMA_URL = "http://localhost:11434/api/generate"
OLLAMA_CHAT_URL = "http://localhost:11434/api/chat"
# MODEL_NAME = "medllama2"
MODEL_NAME = "qwen2.5:7b-instruct-q5_K_M"
VISION_MODEL = "qwen2.5vl:7b"

# Constants
MAX_IMAGE_SIZE = 5 * 1024 * 1024
ALLOWED_IMAGE_TYPES = {"image/jpeg", "image/png", "image/jpg"}

# Global Kokoro pipeline
_KOKORO_PIPELINE = None

def get_kokoro_pipeline(lang_code: str = 'a') -> KPipeline:
    global _KOKORO_PIPELINE
    if _KOKORO_PIPELINE is None:
        if KPipeline is None:
            raise RuntimeError("kokoro package not installed")
        logger.info("Loading Kokoro TTS...")
        _KOKORO_PIPELINE = KPipeline(lang_code=lang_code)
        logger.info("Kokoro TTS loaded")
    return _KOKORO_PIPELINE

def text_to_speech_kokoro(
    text: str,
    voice: str = "af_bella",
    lang_code: str = "a"
) -> bytes:
    if not text.strip():
        raise ValueError("Empty text provided for TTS")

    pipeline = get_kokoro_pipeline(lang_code)

    try:
        generator = pipeline(text, voice=voice)
        audio_chunks = []
        for _, _, audio in generator:
            audio_chunks.append(audio)

        if not audio_chunks:
            raise RuntimeError("No audio generated by Kokoro")

        audio = np.concatenate(audio_chunks)
        audio_int16 = np.int16(audio * 32767)

        byte_io = io.BytesIO()
        with sf.SoundFile(byte_io, mode='x', samplerate=24000, channels=1, format='WAV') as f:
            f.write(audio_int16)
        
        return byte_io.getvalue()

    except Exception as e:
        logger.error(f"Kokoro TTS failed: {str(e)}")
        raise RuntimeError(f"TTS generation error: {str(e)}")

# ===============
# Pydantic Models
# ===============

class SymptomExtractionRequest(BaseModel):
    text: str
    context: Optional[str] = None

class MedicalNoteRequest(BaseModel):
    patient_description: str
    symptoms: Optional[List[str]] = None
    image_analysis: Optional[str] = None
    chat_history: Optional[str] = None  # NEW: Full conversation context

class TextResponse(BaseModel):
    response: str
    model: str

class ImageAnalysisResponse(BaseModel):
    analysis: str
    medical_findings: str
    model: str

class HealthResponse(BaseModel):
    status: str
    ollama_available: bool
    model: str
    vision_model: str

class TTSRequest(BaseModel):
    text: str
    voice: Optional[str] = "af_bella"
    lang_code: Optional[str] = "a"

class ChatMessage(BaseModel):
    session_id: str
    message: str

# ===================
# Helper Functions
# ===================

def call_ollama(
    prompt: str, 
    system_prompt: Optional[str] = None, 
    model: str = MODEL_NAME,
    temperature: float = 0.3,
    max_tokens: int = 600
) -> str:
    start_time = time.time()
    logger.info("=" * 50)
    logger.info(f"CALLING OLLAMA MODEL: {model}")
    logger.info(f"Prompt length: {len(prompt)} characters")
    
    try:
        full_prompt = f"{system_prompt}\n\n{prompt}" if system_prompt else prompt
        
        payload = {
            "model": model,
            "prompt": full_prompt,
            "stream": False,
            "options": {
                "temperature": temperature,
                "top_p": 0.9,
                "num_predict": max_tokens,
                "repeat_penalty": 1.1,
                "num_thread": 4
            }
        }
        
        logger.info("Sending request to Ollama...")
        response = requests.post(OLLAMA_URL, json=payload, timeout=180)
        response.raise_for_status()
        
        result = response.json()
        generated_text = result.get("response", "").strip()
        
        if not generated_text:
            raise ValueError("Model returned empty response")
        
        elapsed = time.time() - start_time
        logger.info(f"Response received: {len(generated_text)} characters")
        logger.info(f"Processing time: {elapsed:.2f} seconds")
        logger.info("=" * 50)
        
        return generated_text
    
    except requests.exceptions.Timeout:
        logger.error("Request timeout")
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Request timed out. The model may be loading. Please try again."
        )
    except requests.exceptions.RequestException as e:
        logger.error(f"Ollama request failed: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Ollama service unavailable: {str(e)}"
        )
    except Exception as e:
        logger.error(f"Unexpected error: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error calling Ollama: {str(e)}"
        )


def call_ollama_vision(prompt: str, image_base64: str) -> str:
    start_time = time.time()
    logger.info("=" * 50)
    logger.info("CALLING VISION MODEL: qwen2.5vl:7b")
    logger.info("=" * 50)
    
    try:
        chat_payload = {
            "model": VISION_MODEL,
            "messages": [{
                "role": "user",
                "content": prompt,
                "images": [image_base64]
            }],
            "stream": False,
            "options": {
                "temperature": 0.2,
                "num_predict": 500,
                "top_p": 0.9,
                "num_thread": 4
            }
        }
        
        logger.info("Trying chat endpoint...")
        response = requests.post(OLLAMA_CHAT_URL, json=chat_payload, timeout=200)
        
        if response.status_code == 200:
            result = response.json()
            content = result.get("message", {}).get("content", "").strip()
            if content and len(content) > 20:
                elapsed = time.time() - start_time
                logger.info(f"Vision analysis complete: {len(content)} chars in {elapsed:.2f}s")
                logger.info("=" * 50)
                return content
        
        logger.info("Chat endpoint unavailable, trying generate endpoint...")
        gen_payload = {
            "model": VISION_MODEL,
            "prompt": prompt,
            "images": [image_base64],
            "stream": False,
            "options": {
                "temperature": 0.2,
                "num_predict": 500,
                "num_thread": 4
            }
        }
        
        response = requests.post(OLLAMA_URL, json=gen_payload, timeout=200)
        response.raise_for_status()
        
        result = response.json()
        content = result.get("response", "").strip()
        
        if not content or len(content) < 20:
            raise ValueError("Vision model returned insufficient response")
        
        elapsed = time.time() - start_time
        logger.info(f"Vision analysis complete: {len(content)} chars in {elapsed:.2f}s")
        logger.info("=" * 50)
        return content

    except requests.exceptions.Timeout:
        logger.error("Vision model timeout")
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Image analysis timed out. Please try again."
        )
    except Exception as e:
        logger.error(f"Vision API error: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Image analysis failed: {str(e)}"
        )


def validate_image_file(file: UploadFile) -> bytes:
    if file.content_type not in ALLOWED_IMAGE_TYPES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid image type. Allowed: {', '.join(ALLOWED_IMAGE_TYPES)}"
        )
    
    contents = file.file.read()
    if len(contents) > MAX_IMAGE_SIZE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Image too large. Max size: 5 MB"
        )
    
    try:
        img = Image.open(BytesIO(contents))
        img.verify()
        
        img = Image.open(BytesIO(contents))
        
        max_dimension = 1536
        if max(img.size) > max_dimension:
            ratio = max_dimension / max(img.size)
            new_size = tuple(int(dim * ratio) for dim in img.size)
            img = img.resize(new_size, Image.Resampling.LANCZOS)
            
            output = BytesIO()
            img.save(output, format=img.format or 'JPEG', quality=90)
            contents = output.getvalue()
            logger.info(f"Image resized to {new_size} for faster processing")
            
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Uploaded file is not a valid image: {str(e)}"
        )
    
    return contents


# ==================
# API ENDPOINTS
# ==================

@app.get("/", response_model=HealthResponse)
def health_check():
    logger.info("Health check requested")
    try:
        resp = requests.get("http://localhost:11434/api/tags", timeout=5)
        ollama_ok = resp.status_code == 200
    except:
        ollama_ok = False
    
    return HealthResponse(
        status="running",
        ollama_available=ollama_ok,
        model=MODEL_NAME,
        vision_model=VISION_MODEL
    )


@app.post("/analyze-image", response_model=ImageAnalysisResponse)
async def analyze_medical_image(
    file: UploadFile = File(...),
    current_user: UserOut = Depends(get_current_user)
):
    logger.info(f"Image analysis requested by user {current_user.id}: {file.filename}")
    
    image_data = validate_image_file(file)
    image_base64 = base64.b64encode(image_data).decode('utf-8')

    analysis_prompt = """You are a clinical expert analyzing a medical image.

STRICT RULES:
1. Describe ONLY what you can clearly see in the image
2. DO NOT make assumptions or guesses about unclear details
3. If something is not visible or unclear, explicitly state "Not clearly visible" or "Cannot determine from image"
4. Be factual and precise

ANALYSIS STEPS:

First, identify the image type:
- Is this MEDICINE (pill/tablet/syrup/medicine packaging/label)?
- OR is this a CLINICAL FINDING (skin condition/wound/rash/X-ray/scan)?

For MEDICINE:
• Drug name (only if clearly visible on label)
• Dosage form (tablet/capsule/syrup/injection)
• Strength (only if label is readable)
• If label is blurry or unclear, state: "Label details not clearly visible"

For CLINICAL FINDING:
• Exact body location visible
• Size (approximate if measurable)
• Color and appearance
• Texture or surface characteristics
• Any visible abnormalities
• State: "Requires clinical examination for definitive diagnosis"

Keep response under 250 words. Be specific and factual only."""

    detailed_analysis = call_ollama_vision(analysis_prompt, image_base64)
    
    if not detailed_analysis or len(detailed_analysis) < 10:
        raise HTTPException(
            status_code=500, 
            detail="Vision model returned empty response"
        )

    findings_prompt = f"""From the following image analysis, extract ONLY the observable facts as bullet points.

Image Analysis:
{detailed_analysis}

RULES:
- Extract only what was directly observed
- Do NOT add interpretations or assumptions
- If analysis stated something was unclear, include that
- Maximum 5 bullet points
- Be concise

Output format:
• Observable finding 1
• Observable finding 2
• Observable finding 3"""

    system_prompt = "You extract factual observations only. No assumptions. No interpretations."
    
    medical_findings = call_ollama(
        findings_prompt, 
        system_prompt,
        temperature=0.1,
        max_tokens=250
    ).strip()
    
    if not medical_findings or len(medical_findings) < 10:
        medical_findings = "• Refer to detailed analysis above for findings"

    return ImageAnalysisResponse(
        analysis=detailed_analysis,
        medical_findings=medical_findings,
        model=VISION_MODEL
    )


@app.post("/extract-symptoms", response_model=TextResponse)
async def extract_symptoms(
    request: SymptomExtractionRequest,
    current_user: UserOut = Depends(get_current_user)
):
    logger.info(f"Symptom extraction requested by user {current_user.id}")
    
    system_prompt = """You are a medical documentation assistant.

YOUR ONLY JOB: Extract symptoms that the patient explicitly stated.

CRITICAL RULES:
- Extract ONLY symptoms directly mentioned by the patient
- DO NOT infer symptoms that weren't stated
- DO NOT interpret vague statements
- DO NOT add related symptoms
- If patient uses unclear language, note it exactly as they said it

You are doing pure extraction, NOT interpretation."""
    
    prompt = f"""Patient's exact statement:
"{request.text}"

Task: List ONLY the symptoms they explicitly mentioned.

Output format:
• Symptom 1 (exactly as patient described)
• Symptom 2 (exactly as patient described)

If NO specific symptoms were clearly stated, output:
"No specific symptoms explicitly stated by patient"

Do not add anything the patient did not say."""
    
    response = call_ollama(
        prompt, 
        system_prompt,
        temperature=0.1,
        max_tokens=350
    )
    
    return TextResponse(response=response, model=MODEL_NAME)


def extract_patient_facts_only(text: str) -> str:
    """
    Extract ONLY factual patient statements, remove all conversational AI content
    """
    if not text:
        return ""

    lines = text.split("\n")
    patient_facts = []
    
    for line in lines:
        line_lower = line.strip().lower()
        
        # ✅ FIXED: More precise filtering
        # Skip lines that are clearly AI/doctor responses
        skip_patterns = [
            "doctor:",
            "assistant:",
            "ai assistant",
            "typing...",
            # Questions (but NOT statements that happen to have "what")
            line_lower.strip().endswith("?"),
            # AI suggestions/recommendations
            "i recommend",
            "i suggest",
            "you should",
            "it would be best",
            "my recommendation",
        ]
        
        # Check if line should be skipped
        should_skip = False
        for pattern in skip_patterns:
            if isinstance(pattern, bool):
                if pattern:  # If it's True (like the endswith check)
                    should_skip = True
                    break
            elif pattern in line_lower:
                should_skip = True
                break
        
        if should_skip:
            continue
            
        # Skip empty lines
        if not line.strip():
            continue
            
        # Keep patient's factual statements
        if line.strip():
            # Remove "Patient:" prefix if exists, but keep "Image" related content
            cleaned = line.replace("Patient:", "").replace("patient:", "").strip()
            if cleaned and len(cleaned) > 3:  # Avoid single words
                patient_facts.append(cleaned)
    
    return "\n".join(patient_facts)

def extract_patient_facts_only(text: str) -> str:
    """
    Extract ONLY factual patient statements, remove all conversational AI content
    """
    if not text:
        return ""

    lines = text.split("\n")
    patient_facts = []
    
    for line in lines:
        line_lower = line.strip().lower()
        
        # Skip AI/doctor responses
        skip_patterns = [
            "doctor:", "assistant:", "ai:", "system:",
            "i recommend", "i suggest", "you should",
            "let me", "i'll help", "i can",
            "would you like", "do you have",
            "my recommendation", "please provide"
        ]
        
        # Check if line should be skipped
        should_skip = False
        for pattern in skip_patterns:
            if pattern in line_lower:
                should_skip = True
                break
        
        # Skip questions
        if line.strip().endswith("?"):
            should_skip = True
            
        if should_skip or not line.strip():
            continue
            
        # Keep patient's factual statements
        cleaned = line.replace("Patient:", "").replace("patient:", "").strip()
        if cleaned and len(cleaned) > 3:
            patient_facts.append(cleaned)
    
    return "\n".join(patient_facts)

@app.post("/generate-medical-note", response_model=TextResponse)
async def generate_medical_note(
    request: MedicalNoteRequest,
    current_user: UserOut = Depends(get_current_user)
):
    logger.info(f"Medical note generation requested by user {current_user.id}")

    # Extract patient facts
    patient_facts = extract_patient_facts_only(
        request.chat_history or request.patient_description
    )
    
    # Validate we have information
    has_patient_info = patient_facts.strip()
    has_image_info = request.image_analysis and request.image_analysis.strip()
    
    if not has_patient_info and not has_image_info:
        raise HTTPException(
            status_code=400,
            detail="No patient information found. Please provide symptoms or upload an image first."
        )

    logger.info("=" * 50)
    logger.info("PATIENT FACTS EXTRACTED:")
    logger.info(patient_facts)
    logger.info("=" * 50)

    # Build clinical data
    clinical_data = []
    if has_patient_info:
        clinical_data.append(f"PATIENT STATEMENTS:\n{patient_facts}")
    if has_image_info:
        clinical_data.append(f"IMAGE FINDINGS:\n{request.image_analysis}")
    
    combined_info = "\n\n".join(clinical_data)

    # ==========================================
    # STEP 1: Determine specialty
    # ==========================================
    specialty_system = """You are a medical expert. Determine the appropriate medical specialty.

RESPOND WITH ONLY ONE WORD - THE SPECIALTY NAME.

Valid specialties: dermatology, ent, cardiology, orthopedics, pediatrics, gynecology, neurology, psychiatry, ophthalmology, gastroenterology, pulmonology, nephrology, urology, endocrinology, rheumatology, general

Examples:
- Skin rash → dermatology
- Chest pain → cardiology
- Kidney issues → nephrology
- Stomach pain → gastroenterology

ONE WORD ONLY."""

    specialty_prompt = f"""Patient Information:
{combined_info}

What is the appropriate medical specialty for this case?"""

    raw_specialty = call_ollama(
        specialty_prompt,
        system_prompt=specialty_system,
        temperature=0.3,
        max_tokens=30
    ).strip()

    logger.info(f"RAW specialty output: {raw_specialty}")

    # Extract only the first word (the specialty)
    specialty_words = raw_specialty.lower().split()
    first_word = specialty_words[0] if specialty_words else ""
    
    # Remove common punctuation
    first_word = first_word.strip('.,!?;:()')

    # Validate specialty
    valid_specialties = [
        "dermatology", "ent", "cardiology", "orthopedics", "pediatrics",
        "gynecology", "neurology", "psychiatry", "ophthalmology",
        "gastroenterology", "pulmonology", "nephrology", "urology",
        "endocrinology", "rheumatology", "general"
    ]
    
    detected_specialty = None
    
    # First try exact match with first word
    if first_word in valid_specialties:
        detected_specialty = first_word
        if detected_specialty == "general":
            detected_specialty = "general medicine"
    
    # If not found, search in full response
    if not detected_specialty:
        for s in valid_specialties:
            if s in raw_specialty.lower():
                detected_specialty = s
                break
    
    # Final fallback
    if not detected_specialty:
        detected_specialty = "general medicine"
    
    logger.info(f"AI detected specialty: {detected_specialty}")

    # ==========================================
    # STEP 2: Generate complete SOAP note with medications
    # ==========================================
    soap_system = f"""You are an experienced {detected_specialty} specialist writing a complete SOAP note with real medications.

CRITICAL RULES:
1. Write a COMPLETE SOAP note based ONLY on the patient information provided
2. In the PLAN section, prescribe 2-4 REAL medications with exact doses
3. Use actual drug names like: Ibuprofen 400mg, Omeprazole 20mg, Amoxicillin 500mg, Hydrocortisone 1% cream
4. DO NOT ask questions or request more information
5. DO NOT use placeholders like [Drug name] or [dose]
6. Work with the information given, even if limited

MANDATORY MEDICATION FORMAT:
1. [Real Drug Name] [exact dose] [route] [frequency] for [duration]

Example for abdominal pain:
1. Omeprazole 20mg Oral once daily before breakfast for 14 days
2. Dicyclomine 20mg Oral TID as needed for cramping for 7 days
3. Ondansetron 4mg Oral TID as needed for nausea for 5 days"""

    soap_prompt = f"""Write a complete SOAP note with real medications for this patient:

PATIENT INFORMATION:
{combined_info}

Write a professional SOAP note with these sections:

SUBJECTIVE:
- Chief Complaint
- History of Present Illness
- Review of Systems

OBJECTIVE:
- Vital Signs (provide standard values if not mentioned)
- Physical Examination findings
- Relevant findings from images/labs if available

ASSESSMENT:
- Primary diagnosis or differential diagnoses with clinical reasoning

PLAN:
Medications: (List 2-4 REAL medications with exact doses, routes, frequency, and duration)
1. 
2.
3.

- Patient education regarding condition management
- Lifestyle modifications as appropriate  
- Monitor symptoms and response to treatment

FOLLOW-UP:
- Return in 1-2 weeks for reassessment
- Seek immediate care if symptoms worsen
- Contact office with questions or concerns

Now write the complete note:"""

    soap_note_raw = call_ollama(
        soap_prompt,
        system_prompt=soap_system,
        temperature=0.4,
        max_tokens=1200
    ).strip()

    # ==========================================
    # STEP 3: Validate and fix if needed
    # ==========================================
    note_lower = soap_note_raw.lower()
    has_real_meds = any(unit in note_lower for unit in ["mg", "ml", "mcg", "g ", "units", "%"])
    has_placeholders = "[" in soap_note_raw and "]" in soap_note_raw
    has_questions = "?" in soap_note_raw and "what" in note_lower
    
    # If AI failed to generate proper medications, create fallback
    if not has_real_meds or has_placeholders or has_questions:
        logger.warning("⚠️ AI failed to generate proper medications, using fallback")
        
        # Generate symptom-based fallback medications
        fallback_meds = generate_fallback_medications(combined_info, detected_specialty)
        
        # Find PLAN section and replace medications
        if "PLAN:" in soap_note_raw:
            parts = soap_note_raw.split("PLAN:")
            before_plan = parts[0]
            
            # Reconstruct with proper medications
            soap_note_raw = f"""{before_plan}
PLAN:
Medications:
{fallback_meds}

- Patient education regarding condition management
- Lifestyle modifications as appropriate
- Monitor symptoms and response to treatment

FOLLOW-UP:
- Return in 1-2 weeks for reassessment
- Seek immediate care if symptoms worsen or new concerning symptoms develop
- Contact office with any questions or concerns"""
        else:
            # If PLAN section missing entirely, append it
            soap_note_raw += f"""

PLAN:
Medications:
{fallback_meds}

- Patient education regarding condition management
- Lifestyle modifications as appropriate
- Monitor symptoms and response to treatment

FOLLOW-UP:
- Return in 1-2 weeks for reassessment
- Seek immediate care if symptoms worsen or new concerning symptoms develop
- Contact office with any questions or concerns"""

    # Clean up any remaining artifacts
    soap_note_raw = soap_note_raw.replace("[", "").replace("]", "")
    
    # Add specialty header
    final_note = f"SPECIALTY: {detected_specialty.upper()}\n\n{soap_note_raw}"

    logger.info("=" * 50)
    logger.info("FINAL GENERATED NOTE:")
    logger.info(f"Specialty: {detected_specialty}")
    logger.info(f"Note length: {len(final_note)} chars")
    logger.info(f"Has real medications: {any(unit in final_note.lower() for unit in ['mg', 'ml', 'mcg', 'g ', 'units', '%'])}")
    logger.info("=" * 50)

    return TextResponse(response=final_note, model=MODEL_NAME)


def generate_fallback_medications(clinical_info: str, specialty: str) -> str:
    """Generate symptom-based fallback medications when AI fails"""
    info_lower = clinical_info.lower()
    meds = []
    
    # Common symptom-based medications
    if "pain" in info_lower or "ache" in info_lower:
        meds.append("1. Ibuprofen 400mg Oral TID with food for 5-7 days")
    
    if "fever" in info_lower or "temperature" in info_lower:
        meds.append(f"{len(meds)+1}. Acetaminophen 500mg Oral Q6H as needed for fever for 5 days")
    
    if "nausea" in info_lower or "vomit" in info_lower:
        meds.append(f"{len(meds)+1}. Ondansetron 4mg Oral TID as needed for nausea for 5 days")
    
    if "acid" in info_lower or "heartburn" in info_lower or "gastro" in info_lower or "abdominal" in info_lower:
        meds.append(f"{len(meds)+1}. Omeprazole 20mg Oral once daily before breakfast for 14 days")
    
    if "cough" in info_lower or "congestion" in info_lower:
        meds.append(f"{len(meds)+1}. Guaifenesin 400mg Oral Q4H as needed for cough for 7 days")
    
    if "rash" in info_lower or "itch" in info_lower or "skin" in info_lower:
        meds.append(f"{len(meds)+1}. Hydrocortisone 1% cream Topical BID to affected areas for 7-14 days")
        meds.append(f"{len(meds)+1}. Cetirizine 10mg Oral once daily for itching for 7 days")
    
    if "anxiety" in info_lower or "stress" in info_lower:
        meds.append(f"{len(meds)+1}. Hydroxyzine 25mg Oral TID as needed for anxiety for 30 days")
    
    # If no specific symptoms matched, provide general supportive care
    if not meds:
        meds = [
            "1. Acetaminophen 500mg Oral Q6H as needed for pain/fever for 5 days",
            "2. Ibuprofen 400mg Oral TID with food as needed for pain for 5 days"
        ]
    
    return "\n".join(meds[:4])  # Max 4 medications
# ==================
# AUTH ENDPOINTS
# ==================

@app.post("/register", response_model=UserOut)
def register(user: UserCreate, db: Session = Depends(get_db)):
    return register_user(user, db)


@app.post("/login", response_model=Token)
def login(
    form_data: OAuth2PasswordRequestForm = Depends(), 
    db: Session = Depends(get_db)
):
    user = get_user_by_email(db, form_data.username)
    if not user or not verify_password(form_data.password, user.hashed_password):
        raise HTTPException(
            status_code=401, 
            detail="Incorrect email or password"
        )
    access_token = create_access_token(data={"sub": user.email})
    return {"access_token": access_token, "token_type": "bearer"}


# ==================
# HISTORY ENDPOINTS
# ==================

class HistoryCreate(BaseModel):
    title: str
    category: Optional[str] = None
    symptoms: Optional[str] = None
    note: str
    date: str

class HistoryUpdate(BaseModel):
    title: Optional[str] = None
    category: Optional[str] = None

class HistoryOut(BaseModel):
    id: int
    title: str
    category: Optional[str]
    date: str
    symptoms: Optional[str]
    note: str
    created_at: datetime

    class Config:
        from_attributes = True


@app.post("/history", response_model=HistoryOut)
def create_history_entry(
    entry: HistoryCreate,
    current_user: UserOut = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    db_entry = ConsultationHistory(
        user_id=current_user.id,
        title=entry.title.strip(),
        category=entry.category.strip() if entry.category else None,
        date=entry.date,
        symptoms=entry.symptoms,
        note=entry.note,
    )
    db.add(db_entry)
    db.commit()
    db.refresh(db_entry)
    return db_entry


@app.get("/history", response_model=List[HistoryOut])
def list_history(
    q: Optional[str] = Query(None, description="Search term"),
    category: Optional[str] = Query(None, description="Filter by category"),
    skip: int = Query(0, ge=0),
    limit: int = Query(50, ge=1, le=200),
    current_user: UserOut = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    query = db.query(ConsultationHistory).filter(
        ConsultationHistory.user_id == current_user.id
    ).order_by(ConsultationHistory.created_at.desc())

    if category and category.lower() != "all":
        query = query.filter(ConsultationHistory.category.ilike(category))

    if q:
        search = f"%{q}%"
        query = query.filter(
            or_(
                ConsultationHistory.title.ilike(search),
                ConsultationHistory.symptoms.ilike(search),
                ConsultationHistory.note.ilike(search)
            )
        )

    results = query.offset(skip).limit(limit).all()
    return results


@app.patch("/history/{entry_id}", response_model=HistoryOut)
def update_history_entry(
    entry_id: int,
    update: HistoryUpdate,
    current_user: UserOut = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    entry = db.query(ConsultationHistory).filter(
        ConsultationHistory.id == entry_id,
        ConsultationHistory.user_id == current_user.id
    ).first()

    if not entry:
        raise HTTPException(404, "Entry not found or not owned by user")

    if update.title is not None:
        entry.title = update.title.strip()
    if update.category is not None:
        entry.category = update.category.strip() if update.category else None

    db.commit()
    db.refresh(entry)
    return entry


@app.delete("/history/{entry_id}")
def delete_history_entry(
    entry_id: int,
    current_user: UserOut = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    entry = db.query(ConsultationHistory).filter(
        ConsultationHistory.id == entry_id,
        ConsultationHistory.user_id == current_user.id
    ).first()

    if not entry:
        raise HTTPException(404, "Entry not found")

    db.delete(entry)
    db.commit()
    return {"status": "deleted", "id": entry_id}


@app.post("/chat")
async def chat_with_ai(
    request: ChatMessage,
    current_user: UserOut = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Conversational medical intake - asks follow-up questions
    """
    system_prompt = """You are a medical professional conducting patient intake.

RULES:
- Ask ONE clear follow-up question at a time
- DO NOT generate diagnosis
- DO NOT suggest medications
- DO NOT write a medical note
- Your goal is to collect complete clinical information

You may ask about:
- Specific symptoms (be precise)
- Duration and onset
- Severity (mild/moderate/severe)
- Location (if applicable)
- Associated symptoms
- Aggravating or relieving factors
- Previous treatments tried
- Temperature if fever mentioned
- Any other relevant clinical details

Keep questions brief and focused."""

    prompt = f"""Patient said: "{request.message}"

Ask the next most relevant follow-up question to gather complete medical history.
Keep it conversational and empathetic."""

    reply = call_ollama(
        prompt,
        system_prompt=system_prompt,
        temperature=0.4,
        max_tokens=120
    )

    return {"reply": reply}




# ==================
# TTS ENDPOINT
# ==================

@app.post("/tts")
async def text_to_speech(
    request: TTSRequest,
    current_user: UserOut = Depends(get_current_user)
):
    if not TTS_AVAILABLE:
        raise HTTPException(
            status_code=503,
            detail="TTS service unavailable. Install kokoro-onnx on server."
        )
    
    try:
        wav_bytes = text_to_speech_kokoro(
            text=request.text,
            voice=request.voice,
            lang_code=request.lang_code
        )

        return Response(
            content=wav_bytes,
            media_type="audio/wav",
            headers={
                "Content-Disposition": "attachment; filename=medical-note.wav",
                "Content-Length": str(len(wav_bytes))
            }
        )

    except Exception as e:
        logger.error(f"TTS endpoint error: {str(e)}")
        raise HTTPException(
            status_code=500, 
            detail=f"TTS generation failed: {str(e)}"
        )


if __name__ == "__main__":
    import uvicorn
    logger.info("=" * 60)
    logger.info("Medical AI Assistant API")
    logger.info("AI Models: medllama2 (text) + qwen2.5vl:7b (vision)")
    logger.info("TTS Engine: Kokoro (text-to-speech only)")
    logger.info("Server: http://0.0.0.0:8001")
    logger.info("API Docs: http://0.0.0.0:8001/docs")
    logger.info("=" * 60)
    uvicorn.run(app, host="0.0.0.0", port=8001)